name: RDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: NSSM & NGROK
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/NflaZ/rdp/master/Files/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/NflaZ/rdp/master/Files/nssm.exe -OutFile nssm.exe
    - name: Copying files to directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Trying to connect on your NGROK's account
      run: .\ngrok.exe authtoken $Env:TOKEN
      env:
        TOKEN: ${{ secrets.TOKEN }}
    - name: Download some files.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/NflaZ/rdp/master/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/NflaZ/rdp/master/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/NflaZ/rdp/master/Files/loop.bat -OutFile loop.bat
    - name: Make some YML's files for NGROK.
      run: start NGROK-US.bat
    - name: RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create some tunnel
      run: sc start ngrok
    - name: Trying to connect to your RDP.
      run: cmd /c NGROK-CHECK.bat
    - name: Done, you can close this site now.
      run: cmd /c loop.bat 
